export const CATS_SEARCH_RANDOM_CAT_BEGIN = 'CATS_SEARCH_RANDOM_CAT_BEGIN';
export const CATS_SEARCH_RANDOM_CAT_SUCCESS = 'CATS_SEARCH_RANDOM_CAT_SUCCESS';
export const CATS_SEARCH_RANDOM_CAT_FAILURE = 'CATS_SEARCH_RANDOM_CAT_FAILURE';
export const CATS_SEARCH_RANDOM_CAT_DISMISS_ERROR = 'CATS_SEARCH_RANDOM_CAT_DISMISS_ERROR';